name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action/go1.13@1.6.0
        with:
          args: make build