name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-37=2.28.1-1 libwebkit2gtk-4.0-dev=2.28.1-1
      - run: make build